export default {
	all: {
		GET_RESV: 'GET_RESV',
		GET_RESV_SUCCEEDED: 'GET_RESV_SUCCEEDED',
		GET_RESV_FAILED: 'GET_RESV_FAILED'
	},
	byId: {
		GET_RESV_BY_ID: 'GET_RESV_BY_ID',
		GET_RESV_BY_ID_SUCCEEDED: 'GET_RESV_BY_ID_SUCCEEDED',
		GET_RESV_BY_ID_FAILED: 'GET_RESV_BY_ID_FAILED'		
	},
	add: {
		ADD_RESV: 'ADD_RESV',
		ADD_RESV_SUCCEEDED: 'ADD_RESV_SUCCEEDED',
		ADD_RESV_FAILED: 'ADD_RESV_FAILED'		
	},
	query: {
		QUERY_RESV: 'QUERY_RESV',
		QUERY_RESV_SUCCEEDED: 'QUERY_RESV_SUCCEEDED',
		QUERY_RESV_FAILED: 'QUERY_RESV_FAILED'		
	},
	RESET_FORM: 'RESET_FORM'
};